### PR TITLE
Detect ERC721 compliant contracts

### LINKED ISSUE #10: Implement a function that ensures a given contract is ERC721 compliant
Quoting @neatonk 
```
you'd be doing a cross contract call to the `supportsInterface` function on the provided contractAddress. 
Lookup the ERC721 spec and see what value to pass to detect support for the ERC721 Interface
```

### PR DESCRIPTION
**Pull request by josealonso**
**Not tested yet.**

### CODE REVIEW

**Comment by josealonso** [comment]
Do not merge it. 
**Not tested yet**

**Comment by neatonk** [comment]
Hi @josealonso. What do you think about using https://docs.openzeppelin.com/contracts/4.x/api/utils#ERC165Checker for this?

**Comment by neatonk** [comment]
Closing since you said not to merge. I'm merging or closing all PR's today to prepare for some repo-restructuring.

**Comment by josealonso** [comment]
> Closing since you said not to merge. I'm merging or closing all PR's today to prepare for some repo-restructuring.

That's fine. I can revisit this issue later.

**Pull request closed without merging**
