### PR TITLE
Reduce size through proxies and other improvements

### LINKED ISSUE #19: Reduce the size of the contract deployed when created a club
A proxy is a small contract, that's why it's cheap to deploy. These tiny contracts have the minimum code to forward the calls to the main contracts. These clones have only state variables referring to one single club, but all the functions are on the main contract, which is ReleaseClub in our case.
This kind of proxy is called a minimal proxy and it's not upgradeable.
I will be using the OpenZeppelin's Clones library.

### PR DESCRIPTION
**Pull request by josealonso**
A proxy is a small contract, that's why it's cheap to deploy. These tiny contracts have the minimum code to forward the calls to the main contracts. These clones have only state variables referring to one single club, but all the functions are on the main contract, which is `ReleaseClub` in our case. 
This kind of proxy is called a minimal proxy and it's **not** upgradeable.
I will be using the OpenZeppelin's **Clones** library.

### CODE REVIEW

**Comment by josealonso** [comment]
Not ready to be merged yet.
I will explain the commits tomorrow.

**Comment by neatonk** [comment]
Very cool. I will be interested in learning more about what you did and what you found along the way.

**Comment by josealonso** [comment]
Not ready to be merged yet. I think it's correctly implemented, but I have issues when deploying the proxy.

**Comment by josealonso** [comment]
- The ReleaseClub contract is the main contract and has been deployed [here](https://rinkeby.etherscan.io/address/0xc103a93b31103c98bd6eda7e9cb177e6093bf6de)
- The Factory contract has been deployed [here](https://rinkeby.etherscan.io/address/0x3e1b4f7c9f20150ffa539c43dc4cb724fd4a8129#events)

As seen in the events page mentioned above, three different clubs have been created.

Etherscan itself says these are **Minimal Proxy Contracts** for the **ReleaseClub** contract.
Each proxy is 54 bytes long, it forwards all the function calls to the main contract. Instead of using the **new** operator, the **Clones** library is used. This is the cheapest way to deploy "copies" of a given contract. 

- For a club to be created, the `createClub` function inside the factory contract has to be called. This function replaces the `addClub` function. 
I changed its name because I think it's more meaningful. 

- The factory functions `viewClubs` and `getClubsByOwner` work fine. 

- I just created a club with a different owner and both functions keep working fine, according to the array returned by the `viewClubs` function:
[link](https://rinkeby.etherscan.io/address/0x3e1b4f7c9f20150ffa539c43dc4cb724fd4a8129#readContract)

**Comment by josealonso** [comment]
This PR is pending approval.

**Review by neatonk — APPROVED** [review]

**Pull request merged**
